### PR TITLE
Url to connect to supports new transport schemes

### PR DESCRIPTION
**Pull request by pfeodrippe**
It was hardcoded to `nrepl` (bencode), now the user
can pass the `scheme` if a different transport
is used.

### CODE REVIEW

**Comment by pfeodrippe** [comment]
up @trptcolin o/

**Comment by bbatsov** [comment]
@pfeodrippe Btw, the build seems to be failing. Not sure if it's related to your changes, though.

**Comment by pfeodrippe** [comment]
> @pfeodrippe Btw, the build seems to be failing. Not sure if it's related to your changes, though.

I think it's related to https://github.com/junit-team/junit4/issues/1577.

I would like to merge this so we can open a PR in `lein` and close the one at `nrepl/fastlane`, but I don't know if @trptcolin has time for this repo anymore... using your OSS expertise, what could we do next, @bbatsov?

**Comment by bbatsov** [comment]
I think @trptcolin still pays attention to the project (most recently he spent a lot of time investigating #197). Probably he just has time to address only very important issues. 

Most likely we have to wait, but I can also propose to him the following - he can make me a collaborator, so I can do nREPL-related updates/changes myself when needed. @trptcolin does this sound like something reasonable to you?

**Comment by trptcolin** [comment]
Yeah, I tend to assume there’s still WIP if the build is failing, so this, along with the other open PRs, has been on the back burner for me.

This looks fine; happy to merge & release when CI goes green! (And if that means a different PR to fix some overarching build problem that’s cool too.)

**Comment by trptcolin** [comment]
Thanks! 🎉

**Comment by pfeodrippe** [comment]
Thank you, @trptcolin and @bbatsov!

**Comment by trptcolin** [comment]
p.s. just invited you as a collaborator @bbatsov - I'm optimistic that eventually https://github.com/bhauman/rebel-readline can subsume usage of REPLy in Leiningen/Boot and REPLy can kind of fade away, but until then... 😄

**Comment by bbatsov** [comment]
Perhaps. I also have high hopes for rebel-readline, but it needs some remote REPL integration before it can get to Lein/Boot. I'm also curious if we can't somehow integrate rebel in REPLy, but probably that'd be a complex endeavour.

**Comment by trptcolin** [comment]
Yep, for sure. It also (via JLine3) would remove support for JDK6-7.

**Pull request merged**
