### PR TITLE
[Fix #181] Update to nREPL 0.4

### LINKED ISSUE #181: Migration plans for nREPL 0.4+
That's basically a follow up of https://github.com/nrepl/nREPL/issues/1 and was also discussed in https://github.com/nrepl/nREPL/issues/4.

I plan to change the namespaces in nREPL in the next release as planned and I'm curious will you be OK to just cut a new release targeting the new nREPL, so I can open PRs for lein and boot as well.

### PR DESCRIPTION
**Pull request by bbatsov**
Here's the discussed migration to nREPL 0.4. As you can see the changes are few and trivial. The only real problem is the dependency to drawbridge, which I didn't expect.

I've pinged @cemerick about it https://github.com/cemerick/drawbridge/issues/23

### CODE REVIEW

**Comment by bbatsov** [comment]
I'm puzzled by the failures - supposedly I've added  properly `tools.logging` to the setup for the test.

**Comment by bbatsov** [comment]
Ah, I found I forgot to update something. OK, the build is officially green then.

**Comment by trptcolin** [comment]
👍 thanks!

**Comment by bbatsov** [comment]
You're welcome! Let me know when you cut a new release, so I can proceed with the rest of the related updates to other projects.

**Comment by trptcolin** [comment]
Released as [0.4.0](https://clojars.org/reply/versions/0.4.0)

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
