### PR TITLE
Fix the deref problem with the latest nREPL version

### PR DESCRIPTION
**Pull request by bbatsov**
I think we should be all good now.

### CODE REVIEW

**Comment by bbatsov** [comment]
Hmm, I'm a bit puzzled by the test failure. Supposedly I've added `nrepl/bencode` properly to the tests. Let me look into this...

**Comment by bbatsov** [comment]
OK, problem fixed. We should be back in business.

**Comment by bbatsov** [comment]
@trptcolin ping :-)

**Comment by trptcolin** [comment]
Thanks! 🎉

**Comment by trptcolin** [comment]
Released as 0.4.2

**Comment by bbatsov** [comment]
Thanks a lot!

**Pull request merged**
