### PR TITLE
Remove unecessary code

### LINKED ISSUE #205: Initialization code breaks `incomplete.core/resolve-class`
It looks like some legacy code was ported over, as the following lines were present before the move to incomplete, merely modified: 

https://github.com/trptcolin/reply/blob/9698d40ca2be8b4b93108e92d3698ef37570d001/src/clj/reply/initialization.clj#L152-L155

In any case, this is strictly nonfunctional as there is a guaranteed arity mismatch. Removing the entire function with `with-redefs` works, and, given that incomplete is a dependency that gets required where it seems to be needed, I'm not sure that this function as a whole is necessary. It seems to enable a development workflow that's no longer needed with lein checkouts and `:deps/root`.

### PR DESCRIPTION
**Pull request by hsartoris-bard**
Fixes #205

### CODE REVIEW

**Comment by bbatsov** [comment]
Okay, now I see that @trptcolin also added some tests in his proposed patch, so I guess that'd be the best course of action for now. And sorry for pitching in so late!

**Comment by trptcolin** [comment]
Yeah @bbatsov @hsartoris-bard if one of y'all have time to update one of your PRs to include a test for the thing that's broken (feel free to grab from that diff above), I'm all for it. 👍 👍 Sorry, a bit slammed today but I should be able to get a release out sometime tomorrow that includes this fix as well as the other two cleanup things @bbatsov.

**Comment by bbatsov** [comment]
@trptcolin I've just updated my PR.

**Comment by trptcolin** [comment]
Going to go ahead and close since we've got the fix in the other PR - thanks y'all!

**Pull request closed without merging**
