### PR TITLE
Bump the nREPL dep

### PR DESCRIPTION
**Pull request by bbatsov**

### CODE REVIEW

**Comment by trptcolin** [comment]
Hey, sorry, I needed to [revert back to nrepl 0.4.2](https://github.com/trptcolin/reply/commit/cefadce20024676428f3933af8da0ed88688359e), because of some breaking changes in 0.4.3 (in particular the structure of `nrepl.server.Server`).

I made a couple new issues for the [missing integration test coverage](https://github.com/trptcolin/reply/issues/186), and the [bump to the latest nrepl](https://github.com/trptcolin/reply/issues/187).

**Comment by bbatsov** [comment]
@trptcolin What breaking changes? The removal of the legacy code from nREPL 0.1 what treated the Server as a ref?

**Comment by bbatsov** [comment]
Seems so. :-) This was deprecated so many years ago that I assumed no one was using this at point. Anyways, at least the fix for this is simple - it's now just a regular record.

**Comment by trptcolin** [comment]
Yeah, I think that and also the field access needs to change from `:ss` to `:server-socket`. And now that I look closer, it looks like the place that threw could be changed to `(:port server)` (instead of drilling through `deref`, `:ss`, `.getLocalPort` (at least as of 2012; based on https://github.com/nrepl/nREPL/commit/8c52a260765103e76c8b8d9f2877fc7f323ada7b)

**Comment by bbatsov** [comment]
Yep, you can access the port directly now.

**Comment by bbatsov** [comment]
Btw, this 0 check is no longer needed as well:

https://github.com/trptcolin/reply/blob/3fb81561c077e40e33b8caaa1432e0daca1ad521/src/clj/reply/eval_modes/nrepl.clj#L159

If there's no port nREPL assumes 0 anyways.

**Comment by bbatsov** [comment]
And sorry for the oversight on my part! I thought I checked explicitly for this, but I guess I didn't.

**Pull request merged**
